codecov:
  ci:
    - github.com
  bot: "codecov-io"

coverage:
  range: "50...70"
  round: down
  precision: 4
  status:
    project:
      default:
        informational: true
    patch:
      default:
        informational: true
        branches:
          - main

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false

ignore:
  - "LICENSES"
  - ".git"
  - "*.yml"
  - "*.yaml"
  - "*.md"
  - "*.bash"
  - "*.zsh"
  - "*.fish"
  - "Makefile"
  - "docs/*"
  - "internal/cmd/.*"
