name: ci

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened]

# See: https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#concurrency.
# This will ensure that only one commit will be running tests at a time on each PR.
concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/setup
    # See: https://qiita.com/atsutama/items/666556ab76ad30637f2d
    # - name: run coverage
    #   run: |
    #     make coverage
    - uses: FedericoCarboni/setup-ffmpeg@v2
      id: setup-ffmpeg
    - run: go test ./... -race -coverprofile=coverage.out -covermode=atomic
    - uses: codecov/codecov-action@v3
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: ./.github/actions/setup
    - run: go build .

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - uses: golangci/golangci-lint-action@v3
